server :
  port : 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmsdemo?characterEncoding=UTF-8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.ncs.demo.po
  mapperLocations: classpath:mapper/*.xml
#配置日志
logging:
  #配置日志文件路径
  path: D:\opt\logs\cms-demo
  level:
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error
    com.ncs.demo.dao: DEBUG